### ISSUE TITLE
Find scope button is missing an edge color

### ISSUE THREAD

**Issue by willco007** [material-theme/nova-material-theme-bugs#1]
If you select the Find sidebar, the find scopes button is missing an edge color for the button. The result is the button divider line isn't drawn correctly.

<img width="178" alt="No divider line color" src="https://user-images.githubusercontent.com/4294739/94041729-7bec9e80-fd7f-11ea-89a7-25a3fb54433f.png">

**Comment by willco007** [comment]
Same thing is happening for the find options in the editor view.

**Comment by equinusocio** [comment]
Does this happen with other themes?

**Comment by equinusocio** [comment]
Seems is now fixed by Nova itself.
